### ISSUE TITLE
Login support?

### ISSUE THREAD

**Issue by ghost** [titaniumnetwork-dev/alloyproxy#16]
It seems that AlloyProxy doesn't work correctly when using google sign-in or Spotify sign-in. Ex: https://accounts.google.com, https://accounts.spotify.com.

I didn't check if they use secretly use  Captcha 2 or something of the sort, and I couldn't check my console (school device).

Has anyone gotten Spotify to work with this proxy yet (logging in)?

Seems like https://www.spotify.com/download/ always redirects, proxy can't get through that either.

**Comment by easella** [comment]
no

**Comment by easella** [comment]
It does not even work with womginx

**Comment by ghost** [comment]
Yeah, none of them worked for this.

@shirt-dev
Do you or any of the other developers need any information to figure out how to make these logins work? I could try to investigate if you do.

**Comment by easella** [comment]
Pydodge may work

**Comment by easella** [comment]
not even pydodge works

**Comment by dontlikeya-lol** [comment]
if you guys also make it so pinterest, and instagram works (ie: image loading improvement, sign in, redirects) and allow for more support on other websites, that would be cool.

**Comment by easella** [comment]
pydodge works for instagram

**Comment by dontlikeya-lol** [comment]
okay, thank you! do you know any proxies that work for tiktok? (signing in, etc)

**Comment by easella** [comment]
alloyproxy works for tiktok(i think)
try my  unblocked games site:[click here](https://geometrypractice.glitch.me)
it uses proxy websites
it has tiktok
if your school blocks repl.co, heroku, or codesandbox.io, some games will be blocked

**Comment by easella** [comment]
does alloyproxy work for instagram

**Comment by easella** [comment]
do you know of any proxies that work for tiktok?

**Comment by dontlikeya-lol** [comment]
yes, i think pydodge works for tiktok but you cant sign in

**Comment by easella** [comment]
oh you cant?
not even with qr code?

**Comment by easella** [comment]
pydodge doesnt work for tiktok at all
![image](https://user-images.githubusercontent.com/74786054/117019950-ed041500-acc3-11eb-8fce-7fb6b5d722c8.png)

**Comment by easella** [comment]
did u try my unblocked games site?

**Comment by MrMachi9** [comment]
yea i did its really fun

**Comment by easella** [comment]
are any games blocked? 
Is heroku blocked for securely?

**Comment by dontlikeya-lol** [comment]
😓

**Comment by easella** [comment]
they are?

**Comment by MrMachi9** [comment]
no

**Comment by MrMachi9** [comment]
covidstatistics.glitch.me

**Comment by easella** [comment]
i change the url daily
here r some more links:
[click here](https://divisionpractice.glitch.me)
[click here](https://warp-tary-poet.glitch.me)
by the way i figured out how 2 unblock krunker(its very laggy though)
[click here](https://vps.apponfly.com)

**Comment by MrMachi9** [comment]
this is so cool your the coolest person ever

**Comment by easella** [comment]
thank you

**Comment by MrMachi9** [comment]
its ok

**Comment by MrMachi9** [comment]
you know just yesterday one of the links were blocked and i just got a new one

**Comment by easella** [comment]
lol
it took my school 2 months to block the first link

**Comment by easella** [comment]
heres another link:
[click here](https://ioh1h.sse.codesandbox.io/)

**Comment by ghost** [comment]
Please, could the three of you could take your disussion elsewhere? I'd like to focus only on making the repository's proxy effective where it currently doesn't work.

**Comment by easella** [comment]
oh.fine.
by the way can you make this proxy work with netflix?
when i click the login button it navigates to the about:blank page
try it out yourself:[click here](https://partialvirtualredundancy-1.awdrgyjil1234.repl.co/web/_aHR0cHM6Ly93d3cubmV0ZmxpeC5jb20=_/login)

**Comment by MrMachi9** [comment]
does it have war brokers.io

**Comment by MrMachi9** [comment]
and if it dosent can you add it

**Comment by easella** [comment]
no

**Comment by easella** [comment]
sorry

**Comment by MrMachi9** [comment]
can you add polyblicy

**Comment by MrMachi9** [comment]
or repuls.io

**Comment by dontlikeya-lol** [comment]
I hope they add Google login support.

**Comment by easella** [comment]
i cant add repuls io

**Comment by MrMachi9** [comment]
what about polyblicy

**Comment by easella** [comment]
no

**Comment by MrMachi9** [comment]
ok

**Comment by easella** [comment]
sorry

**Comment by nab138** [comment]
+1 for google login support, I would love to access chrome remote desktop

**Comment by dontlikeya-lol** [comment]
dont you need a computer for that

**Comment by MrMachi9** [comment]
yea

**Comment by MrMachi9** [comment]
laud i know your here

**Comment by MrMachi9** [comment]
i cant login to any thing i just found that out

**Comment by nab138** [comment]
@dontlikeya-lol yes, you do need a computer for that. I'm saying I would like to access my home computer from elsewhere on a device where chrome remote is blocked.
