### ISSUE TITLE
heroku error?

### ISSUE THREAD

**Issue by JaxGamez** [titaniumnetwork-dev/alloyproxy#19]
deployed to heroku, app error. is something broken?

**Comment by Nebelung-Dev** [comment]
It works for me...

**Comment by easella** [comment]
maybe your dynos expired. you will have to wait till next month for it to work.

**Comment by JaxGamez** [comment]
just realized that they did xD

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
