### ISSUE TITLE
Why won't css load into the repl

### ISSUE THREAD

**Issue by LuffyRequiem** [titaniumnetwork-dev/alloyproxy#20]
![aaaaa](https://user-images.githubusercontent.com/68499840/113484341-ce68ef00-9475-11eb-97fe-799806a4bdc0.png)

**Comment by easella** [comment]
modify the index.html file so it looks like this:
![Uploading image.png…]()

**Comment by easella** [comment]
modify the html file so it looks like this:
![Uploading image.png…]()

**Comment by easella** [comment]
modify the index.html file so it looks like this:
![image](https://user-images.githubusercontent.com/74786054/113322579-dd6b6800-92e2-11eb-95fc-326190f5a363.png)

**Comment by LuffyRequiem** [comment]
what exactly changed?

**Comment by easella** [comment]
i changed line 3.

**Comment by LuffyRequiem** [comment]
i got the CSS and HTML in a separate file.

**Comment by QuiteAFancyEmerald** [comment]
Um, can you explain a bit more about your setup?

**Comment by LuffyRequiem** [comment]
i just forked it and followed the instructions and that happens

**Comment by onlycs** [comment]
i wrote my own css:
https://crazycoder691-unblocked-sites.herokuapp.com
https://github.com/dragonBall561/unblocked-sites

**Comment by easella** [comment]
hey everyone try my games site:
[click here](https://games.awdrgyjil1234.repl.co/)
If your school uses contentkeeper it will be unblocked.

**Comment by LuffyRequiem** [comment]
unfortunately, Heroku is blocked for securly and I can only use replit.

**Comment by LuffyRequiem** [comment]
but I've already figured it out so it's fine.
