### ISSUE TITLE
Certain .io sites not working (krunker, mope, wiziz, zombs, diep, moomoo, leevz, taming, tyran, and wings.io not working)

### ISSUE THREAD

**Issue by easella** [titaniumnetwork-dev/alloyproxy#22]
here are the screenshots.
![image](https://user-images.githubusercontent.com/74786054/113322748-14da1480-92e3-11eb-8f83-3d7fa30942d0.png)

![image](https://user-images.githubusercontent.com/74786054/114328435-a0854980-9b0a-11eb-9f6e-bb613c43904e.png)

![image](https://user-images.githubusercontent.com/74786054/114328460-b430b000-9b0a-11eb-9b3c-3e6f70a3e143.png)

![image](https://user-images.githubusercontent.com/74786054/114328477-c4e12600-9b0a-11eb-90c2-1a70a3a648a0.png)

![image](https://user-images.githubusercontent.com/74786054/114328498-d1fe1500-9b0a-11eb-8d51-e10c64d7533a.png)

![image](https://user-images.githubusercontent.com/74786054/114328542-f6f28800-9b0a-11eb-90d9-54f5a41a12a9.png)

![image](https://user-images.githubusercontent.com/74786054/114328600-1c7f9180-9b0b-11eb-885c-3ed315d18525.png)
![image](https://user-images.githubusercontent.com/74786054/114328752-8009bf00-9b0b-11eb-8b6c-b52884bc70fa.png)
![image](https://user-images.githubusercontent.com/74786054/114328776-931c8f00-9b0b-11eb-8b4c-4b175c2fd9ff.png)

**Comment by caracal-js** [comment]
Hello, I am currently aware that Krunker.io does not work due to use of the `location` object and it not being rewritten properly which is causing issues with making requests to matchmaking. This is hopefully to change in the future with better rewriting.

**Comment by easella** [comment]
please fix it. I love krunker and a lot of people want me to add it to  my games website.

**Comment by MrMachi9** [comment]
can i please get krunker

**Comment by MrMachi9** [comment]
i wanna play it so bad and its blocked

**Comment by easella** [comment]
hey MrMachi9, try my games site. here is the link: [click here](https://games.awdrgyjil1234.repl.co/)
it uses proxy sites and is unblocked at my school.

**Comment by MrMachi9** [comment]
its blocked

**Comment by easella** [comment]
Does your school block repl.co?
