### ISSUE TITLE
mope io not working

### ISSUE THREAD

**Issue by easella** [titaniumnetwork-dev/alloyproxy#24]
it is simply stuck on this screen forever.
![image](https://user-images.githubusercontent.com/74786054/113789265-d1314180-970c-11eb-8aea-70b96e0ab21c.png)

**Comment by QuiteAFancyEmerald** [comment]
Can you by chance combine all of your issues with certain .io games into one issue? It's somewhat spammy (no offense).

Do this in the Krunker issue you opened up.

**Comment by easella** [comment]
ok i did

**Comment by QuiteAFancyEmerald** [comment]
epic :D
