### ISSUE TITLE
error code 431

### ISSUE THREAD

**Issue by lilwhip223** [titaniumnetwork-dev/alloyproxy#26]

**Comment by easella** [comment]
what do you mean?

**Comment by lilwhip223** [comment]
now it says hmmmmmmmm we couldnt rechth this replit
On Mon, Apr 19, 2021 at 12:24 PM easella ***@***.******@***.***> wrote:
what do you mean?

**Comment by easella** [comment]
oh yeah simply stop the repl and run it again

**Comment by lilwhip223** [comment]
wait now its says page not working
On Tue, Apr 20, 2021 at 9:32 AM easella ***@***.******@***.***> wrote:
oh yeah simply stop the repl and run it again

**Comment by lilwhip223** [comment]
now its say hmmm we couldn't reach your repl it
On Tue, Apr 20, 2021 at 10:04 AM Kevin Davila-Garcia ***@***.******@***.***> wrote:
wait now its says page not working
On Tue, Apr 20, 2021 at 9:32 AM easella ***@***.******@***.***> wrote:
oh yeah simply stop the repl and run it again

**Comment by easella** [comment]
do what I told you!

**Comment by easella** [comment]
i think its simply that the alloyproxy cant handle a lot of requests at one time so it simply crashes
