### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by easella** [titaniumnetwork-dev/alloyproxy#28]
all it does is reload the page and then the recaptcha does not show up
![image](https://user-images.githubusercontent.com/74786054/116020147-b79c5f00-a613-11eb-92f4-d17d73279eaf.png)

**Comment by LuffyRequiem** [comment]
yeah do you guys have a way around this
![lunch](https://user-images.githubusercontent.com/68499840/116586562-9c697200-a8e7-11eb-8f7f-97baa86594ad.jpg)

**Comment by QuiteAFancyEmerald** [comment]
#10

**Comment by easella** [comment]
i think womginx works for that type of cloudflare protection thing

**Comment by QuiteAFancyEmerald** [comment]
Yeah since Womginx has reCAPTCHA support.
