### ISSUE TITLE
Is this still being updated?

### ISSUE THREAD

**Issue by easella** [titaniumnetwork-dev/alloyproxy#37]

**Comment by SpottedNewbie** [comment]
maybe. I've made a branch with google auth embeded

**Comment by easella** [comment]
when will it be ready?

**Comment by easella** [comment]
you mean you can finally login into google?

**Comment by easella** [comment]
also make it so when you go to youtube it does nor show the cannot get /watch error

**Comment by easella** [comment]
show the branch to me

**Comment by SpottedNewbie** [comment]
> when will it be ready?

I'm still working on it. It's a whitelist system so that teachers/employers can't get to the site.

> show the branch to me

Add me on Discord, P1xelized#2014
