### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Lofi-Lemonade** [titaniumnetwork-dev/alloyproxy#6]
Discord Doesn't work whenever you try to log in it says this 
![image](https://user-images.githubusercontent.com/63267483/96355430-9b8d9300-10af-11eb-9f78-8cbc44a1caae.png)
Please fix this :(

**Comment by trentwiles** [comment]
This proxy doesn't support discord.

**Comment by Lofi-Lemonade** [comment]
Oh :(
![image](https://user-images.githubusercontent.com/63267483/96386065-1618ea00-1166-11eb-93e6-5325f6074e0e.png)

**Comment by trentwiles** [comment]
Not sure why they have discord there, I can explain why it probably will not work.

Google captcha detects what website the captcha is being executed on. In this case, it would be the proxy website. Google would only render the code on *.discord.com or *.discordapp.com which is why it will not work.

**Comment by Lofi-Lemonade** [comment]
OH thank you!

**Comment by shirt-dev** [comment]
Quick note, you can use the QR code to login.

**Comment by caracal-js** [comment]
> 
> 
> This proxy doesn't support discord.

It does, use QR code

**Comment by easella** [comment]
i found a proxy that works for discord( no qr code required):https://extremely-fast-dog.herokuapp.com/lesson/https://discord.com

**Comment by caracal-js** [comment]
> 
> 
> i found a proxy that works for discord( no qr code required):https://extremely-fast-dog.herokuapp.com/lesson/https://discord.com

 Ah yes Womginx is a very powerful proxy however your reply does not concern anything related to Alloy.

**Comment by easella** [comment]
actually womginx does not work for discord. anyone know a proxy that works for discord?

**Comment by easella** [comment]
you are right.
womginx works for discord and hulu!

**Comment by SpottedNewbie** [comment]
Discord now works because they now use HCaptcha instead of Recaptcha. Thank discord for this change.
