### ISSUE TITLE
How can i change it so that images work?

### ISSUE THREAD

**Issue by LuffyRequiem** [titaniumnetwork-dev/alloyproxy#7]
@shawtylikeamelody

**Comment by QuiteAFancyEmerald** [comment]
For what? That is an incredibly vague question.

**Comment by LuffyRequiem** [comment]
On google 
if i search something and go to google images it shows a black page
but on some websites images show
-luffy

**Comment by trentwiles** [comment]
Can you send a screenshot?

**Comment by LuffyRequiem** [comment]
![Screenshot 2020-12-16 at 12 02 39 PM](https://user-images.githubusercontent.com/68499840/102381207-f0a63200-3f96-11eb-8094-4e8a8af44e49.png)
![Screenshot 2020-12-16 at 12 03 12 PM](https://user-images.githubusercontent.com/68499840/102381244-fac83080-3f96-11eb-9af9-e4453202f715.png)
when i press on the images tab the page just becomes blank

**Comment by trentwiles** [comment]
Can you try a different search engine luck DuckDuckGo and Bing?

**Comment by LuffyRequiem** [comment]
Thanks bing works
